Update dependencies list, fix travis syntax
Changelog: None

Issues: MEN-1860

Signed-off-by: Adam Podogrocki <a.podogrocki@gmail.com>

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,9 +1,9 @@
-language: go 
+language: go
 
 sudo: false
 
 os:
-    -linux
+    - linux
 
 go:
     - 1.10.x
@@ -25,15 +25,37 @@ install: true
 before_script:
 
 script:
-    - ./client-cross-compilation-tool.sh build -p Cortex-A8
-    - if [[ ! -d $TOOLCHAIN_PATH/$TOOLCHAIN ]]; then 
-        echo -e "\nError: tool-chain build failure."
-        exit 1
-      fi
-    - ./go-executable-build.sh -n github.com/mendersoftware/mender -p Cortex-A8
-    - if [[ ! -f $MENDER ]]; then
-        echo - "\nError: mender client binary not found."
-        exit 1
-      fi
-    - cpu=($($TOOLCHAIN_PATH/$TOOLCHAIN/bin/$TOOLCHAIN-readelf $MENDER -a | grep 'Tag_CPU_name' | tr -s ' ' | cut -d' ' -f3))
-      [[ $cpu == '"Cortex-A8"' ]] && { echo "Success."; exit 0; } || { echo "Failure. Binary file attributes mismatch."; exit 1 }
+  - |
+    ./client-cross-compilation-tool.sh build -p Cortex-A8
+    ret=$?
+    if [[ $ret -ne 0 ]]; then
+      echo -e "\nError: toolchain build failure."
+      exit $ret
+    fi
+  - |
+    if [[ ! -d "${TOOLCHAIN_PATH}/${TOOLCHAIN}" ]]; then
+      echo -e "\nError: invalid toolchain path."
+      exit 1
+    fi
+  - |
+    PATH="${PATH}:${TOOLCHAIN_PATH}/${TOOLCHAIN}/bin"
+    ./go-executable-build.sh -n github.com/mendersoftware/mender -p Cortex-A8
+    ret=$?
+    if [[ $ret -ne 0 ]]; then
+      echo -e "\nError: Mender client binary build failure."
+      exit $ret
+    fi
+  - |
+    if [[ ! -f $MENDER ]]; then
+      echo - "\nError: mender client binary not found."
+      exit 1
+    fi
+  - |
+    cpu=($($TOOLCHAIN_PATH/$TOOLCHAIN/bin/$TOOLCHAIN-readelf $MENDER -a | grep 'Tag_CPU_name' | tr -s ' ' | cut -d' ' -f3))
+    if [[ $cpu == '"Cortex-A8"' ]]; then
+      echo "Success."
+      exit 0
+    else
+      echo "Failure. Binary file attributes mismatch."
+      exit 1
+    fi
